[theme]
backgroundColor="#f4e8e0"
secondaryBackgroundColor="#c08416"
font = "Cormorant Garamond:https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&display=swap"
textColor = "#d92958"
