[theme]
backgroundColor="#f4e8e0"
secondaryBackgroundColor="#f4e8e0"
font = "Cormorant Garamond:https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&display=swap"
textColor = "#3c8d6b"
