[theme]
backgroundColor="#f4e8e0"
secondaryBackgroundColor="#e65f46"
font = "Cormorant Garamond:https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&display=swap"
textColor = "#050505"
